apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 2
  roles:
    - broker
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 20Gi
        deleteClaim: true
  resources:
    limits:
      cpu: 2
      ephemeral-storage: 1Gi
      memory: 4Gi
    requests:
      cpu: 1
      ephemeral-storage: 1Gi
      memory: 2Gi
---


apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 4.0.0
    template:
      pod:
        tmpDirSizeLimit: 256Mi
    config:
      log.retention.check.interval.ms: 60000
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 2
      default.replication.factor: 2
      min.insync.replicas: 2
      num.partitions: 2
      auto.create.topics.enable: false
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
  entityOperator: # (27)
    topicOperator: {}
    userOperator: {}