apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie
  labels:
    app: movie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: movie
    spec:
      imagePullSecrets:
        - name: image-pull-secret
      containers:
        - name: movie
          image: $CONTAINER_REGISTRY/movie-service:$VERSION
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9006
            - containerPort: 8006
          env:
            - name: SERVER_PORT
              value: "9006"
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: BPL_DEBUG_ENABLED
              value: "true"
            - name: BPL_DEBUG_PORT
              value: "8006"
            - name: SPRING_KEYCLOAK_SERVER_URL
              value: "http://moviebets-keycloak:8080/keycloak"
            - name: SPRING_KEYCLOAK_SERVER_EXTERNAL_URL
              valueFrom:
                configMapKeyRef:
                  name: base-url-config
                  key: KEYCLOAK_BASE_URL
            - name: INSTANCE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]

---
apiVersion: v1
kind: Service
metadata:
  name: movie
  labels:
    app: movie
spec:
  selector:
    app: movie
  ports:
    - name: prod
      port: 9006
      targetPort: 9006
    - name: debug
      port: 8006
      targetPort: 8006