apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviebets-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moviebets-ui
  template:
    metadata:
      labels:
        app: moviebets-ui
    spec:
      imagePullSecrets:
        - name: image-pull-secret
      containers:
        - name: moviebets-ui
          image: $CONTAINER_REGISTRY/moviebets-ui:$VERSION
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_SERVER_SIDE_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: base-url-config
                  key: SERVER_SIDE_BASE_URL
            - name: NEXT_PUBLIC_KEYCLOAK_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: base-url-config
                  key: KEYCLOAK_BASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: moviebets-ui
spec:
  selector:
    app: moviebets-ui
  ports:
    - name: moviebets-ui
      protocol: TCP
      port: 3000
      targetPort: 3000
